---
# Requirements
requirements:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

docker_autostart: yes

# Edition can be 'ce' (Community Edition) or 'ee' (Enterprise Edition).
docker_edition: 'ce'
docker_version: '17.06.2.ce'
#docker_centos: 'el7.centos.x86_64'
#docker_package: "docker-{{ docker_edition }}-{{ docker_version }}.{{ docker_centos }}"
docker_package: "docker-{{ docker_edition }}-{{ docker_version }}"
docker_package_state: present
# docker_version_centos: "docker-ce-17.06.1.ce"
# docker_version_centos: "docker-ce-17.06.2.ce"
# docker-ce-17.09.1.ce-1.el7.centos.x86_64

# Docker Compose version and path
docker_install_compose: true
docker_compose_version: "1.16.1"
docker_compose_path: /usr/local/bin/docker-compose

# Used only for Debian/Ubuntu. Switch 'stable' to 'edge' if needed.
docker_apt_release_channel: stable
docker_apt_repository: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"

# Yum Repo (RedHat/CentOS).
docker_yum_repo_url: https://download.docker.com/linux/centos/docker-{{ docker_edition }}.repo
docker_yum_repo_enable_edge: 0
docker_yum_repo_enable_test: 0