---
- import_tasks: install-docker-centos.yml
  when: ansible_os_family == 'RedHat'

- name: Install Docker.
  package: name={{ docker_package }} state={{ docker_package_state }}

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: yes

# Enable docker autostart
- name: Set docker container service autostart to enabled.
  command: echo "Set docker container service autostart to enabled"
  notify:
    - enable autostart docker
  when: docker_autostart

- name: Execute handlers before verifying docker installation.
  meta: flush_handlers

- name: Verify docker installation.
  command: docker run hello-world
  register: docker_output

- debug:
    var: docker_output.stdout_lines
    
- import_tasks: install-docker-compose.yml
  when: docker_install_compose