version: "3"
services:
    artifactory:
      image: docker.bintray.io/jfrog/artifactory-pro
      restart: always
      ports: 
        - 8081:8081
      networks:
        - devnet
volumes:
  artifactory-data:

networks:
  devnet:
