version: "3"
services:
    telegraf:
      image: telegraf:1.3.4-alpine
      restart: "no"
      ports:
        - 8092:8092/udp
        - 8125:8125/udp
        - 8094:8094
      networks:
        - devnet
    httpd:
      image:  httpd:2.4.25-alpine
      restart: "no"
      ports: 
        - 443:443
        - 80:80
        - 25000:25000
      volumes:
        - /data/httpd/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
        - /data/artifactory-ssl:/artifactory-ssl
      networks:
        - devnet
    artifactory:
      image: docker.bintray.io/jfrog/artifactory-pro:5.3.1
      restart: "no"
      ports: 
        - 8081:8081
      volumes:
        - artifactory-data:/var/opt/jfrog/artifactory
      networks:
        - devnet
volumes:
  artifactory-data:

networks:
  devnet:
